import { useState } from "react";
export const Rd = () => {
  const [randomJoke, setjoke] = useState("");
  const jokes = [
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call fake spaghetti? An impasta!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "I told my friend 10 jokes to make him laugh. Sadly, no pun in ten did.",
    "Parallel lines have so much in common. It’s a shame they’ll never meet.",
    "Why can’t you give Elsa a balloon? Because she will let it go.",
    "Why did the math book look sad? It had too many problems.",
    "Why don’t eggs tell jokes? Because they might crack up.",
    "What do you call cheese that isn’t yours? Nacho cheese.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why do cows have hooves instead of feet? Because they lactose.",
    "What’s orange and sounds like a parrot? A carrot.",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why don’t some couples go to the gym? Because some relationships don’t work out.",
    "What do you call a factory that makes good products? A satisfactory.",
    "Why couldn’t the leopard hide? Because he was always spotted.",
    "Did you hear about the kidnapping at school? It’s fine, he woke up.",
    "Why did the golfer bring an extra pair of pants? In case he got a hole in one.",
    "What do you call an alligator in a vest? An investigator.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What’s brown and sticky? A stick.",
    "What did one hat say to the other? Stay here, I’m going on ahead.",
    "What’s the best way to watch a fly-fishing tournament? Live stream.",
    "Why do seagulls fly over the ocean? Because if they flew over the bay, they’d be bagels.",
    "How does a penguin build its house? Igloos it together.",
    "Why did the coffee file a police report? It got mugged.",
    "What’s a skeleton’s least favorite room in the house? The living room.",
    "Why couldn’t the bicycle find its way home? It lost its bearings.",
    "Why do bees have sticky hair? Because they use honeycombs.",
    "What’s blue and not heavy? Light blue.",
    "Why was the belt arrested? For holding up a pair of pants.",
    "Why don’t vampires go to barbecues? They don’t like steaks.",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine.",
    "Why can’t you trust an ? Because they make up everything.",
    "What do you call an illegally parked frog? Toad.",
    "Why did the chicken go to the seance? To talk to the other side.",
    "What does a house wear? Address.",
    "Why did the banana go to the doctor? Because it wasn’t peeling well.",
    "Why did the fish blush? Because it saw the ocean’s bottom.",
    "What’s the best thing about Switzerland? I don’t know, but the flag is a big plus.",
    "Why did the computer catch a cold? It left its Windows open.",
    "Why was the broom late? It swept in.",
    "What did the left eye say to the right eye? Between you and me, something smells.",
    "What kind of music do mummies listen to? Wrap music.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "How do you make a tissue dance? Put a little boogie in it.",
    "Why did the mushroom go to the party? Because he was a fungi.",
    "What do you call a bear with no teeth? A gummy bear.",
    "What did one wall say to the other wall? I’ll meet you at the corner.",
    "Why don’t bakers make good baseball players? Because they always knead a break.",
    "Why did the chicken sit on the eggs? Because it wanted to hatch a plan.",
    "Why don’t skeletons play music in church? Because they have no organs.",
    "What kind of shoes do ninjas wear? Sneakers.",
    "Why are ghosts bad liars? Because they are too transparent.",
    "Why do cows wear bells? Because their horns don’t work.",
    "What did the buffalo say to his son when he left for college? Bison.",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus.",
    "Why don’t oysters donate to charity? Because they’re shellfish.",
    "What do you call a sleeping bull? A bulldozer.",
    "Why did the cow jump over the moon? Because the farmer had cold hands.",
    "Why did the clock break up with the calendar? It needed more time.",
    "What’s the loudest pet? A trumpet.",
    "Why was the tomato blushing? Because it saw the salad dressing.",
    "Why don’t skeletons go trick-or-treating? They have no body to go with.",
    "Why do elephants never use computers? Because they’re afraid of the mouse.",
    "Why did the golfer wear two pairs of pants? In case he got a hole in one.",
    "What do you call a boomerang that doesn’t come back? A stick.",
    "What do you call a can opener that doesn’t work? A can’t opener.",
    "Why was the math book unhappy? It had too many problems.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why did the stadium get hot? Because all the fans left.",
    "Why don’t crabs give to charity? Because they’re shellfish.",
    "How do you organize a space party? You planet.",
    "What’s a cat’s favorite color? Purr-ple.",
    "What did one plate say to the other plate? Dinner’s on me.",
    "What kind of dog does magic tricks? A labracadabrador.",
    "What did the zero say to the eight? Nice belt!",
    "Why was the broom late? It swept in.",
    "What did the fisherman say to the magician? Pick a cod, any cod.",
    "Why did the banker switch careers? He lost interest.",
    "What’s a snake’s favorite subject? Hiss-tory.",
    "Why did the grape stop rolling? Because it ran out of juice.",
    "Why don’t cannibals eat clowns? Because they taste funny.",
    "What do you call a broken boomerang? A stick.",
    "Why was the math teacher suspicious? He smelled something fishy.",
    "Why did the smartphone go to therapy? Because it lost its touch.",
    "Why are ghosts such bad liars? Because you can see right through them.",
    "Why do bicycles fall over? Because they’re two-tired.",
    "Why did the belt get arrested? For holding up pants.",
    "What do you call a pig that knows karate? A pork chop.",
    "Why did the cookie cry? Because his mom was a wafer so long.",
    "Why did the astronaut break up with his girlfriend? He needed space.",
  ];
  return (
    <>
      <div className="cen">
        <div className="cen2">
          <button
            onClick={() =>
              setjoke(jokes[Math.floor(Math.random() * jokes.length)])
            }
          >
            Generate Random Joke :
          </button>
          <p>{randomJoke}</p>
        </div>
      </div>
    </>
  );
};
